# Generated by Django 2.1.3 on 2018-12-01 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('check', '0002_auto_20181201_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MProfile',
        ),
        migrations.AlterModelOptions(
            name='mprofile',
            options={},
        ),
    ]
