# Generated by Django 2.1.3 on 2018-12-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20181201_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField(verbose_name='SSN')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.MProfile')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
