# Generated by Django 2.1.3 on 2018-12-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['ssn']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
