# Generated by Django 2.1.3 on 2018-12-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20181201_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='u',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
