# Generated by Django 2.1.3 on 2018-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20181201_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mprofile',
            name='ssn',
            field=models.IntegerField(default=0),
        ),
    ]
