# Generated by Django 2.1.3 on 2018-12-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20181202_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mprofile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='mprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mprofile',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='mprofile',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='mprofile',
            name='ssn',
        ),
    ]
